spring:
  thymeleaf:
    #prefix: classpath:templates/
    check-template-location: true
    suffix: .html
    mode: HTML
    encoding: UTF-8
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  mvc:
    static-path-pattern: /static/**
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
debug: true

clipboard:
  config:
    object-count: 3
